### ISSUE TITLE
Create a new release 0.4

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/python_dhcp_server#9]
@greggzj, this can be a new release: https://github.com/niccokunzmann/python_dhcp_server/releases/tag/0.4
What would be nice for windows users, to have the standalone zip file. Are you willing to create this file?

Related: https://github.com/niccokunzmann/python_dhcp_server/pull/8#discussion_r293215729

**Comment by greggzj** [comment]
Wow sounds interesting. 

I use this package for automation test and do not use GUI window. So previously I only care about the low level `dhcp.py` and `listener.py` :)

Frankly speaking I am fresh on pyw format file, but it sounds interesting to generate a singlealong execution file for windows users. Are you use package tool like pyinstaller to package the `pyw` into single alone execution file ? If so, could you recommend any guide or command options when for packaging ? Thanks in advance!

**Comment by niccokunzmann** [comment]
I use python portable. To create the release file, you can unzip it, replace the files from the repository and zip it and upload.

**Comment by greggzj** [comment]
[python_dhcp_server_standalone.zip](https://github.com/niccokunzmann/python_dhcp_server/files/3300104/python_dhcp_server_standalone.zip)

Hello @niccokunzmann , sorry for the delay, above is the windows standalone zip file related to  #8 . 
Not sure whether this is what you want. 

Hoping for the release releated to #10   ^_^

**Comment by niccokunzmann** [comment]
@greggzj, would you like to create this release?

**Comment by greggzj** [comment]
wow...why not...
But how do I create this release？By adding me to collaborator for this repository or by other means?

**Comment by niccokunzmann** [comment]
Yes, exactly. You are invited to shape it to your liking in consideration of other users' needs and expectations. https://github.com/niccokunzmann/python_dhcp_server/invitations
